language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t kho226/reading-list-frontend -f frontend/Dockerfile.dev .
  - docker build -t kho226/reading-list-backend -f backend/Dockerfile.dev .

script:
  - docker run -e CI=true kho226/reading-list-frontend go test -v -cover ./...
  - docker run -e CI=true kho226/reading-list-backend go test -v -cover ./...
