sudo: required
services: 
  - docker

before_install:
  - docker build -t kho226/reading-list-frontend -f frontend/Dockerfile.dev .
  - docker build -t kho226/reading-list-backend -f backend/Dockerfile.dev .

scripts:
  - docker run kho226/reading-list-frontend go test -v -cover ./...
  - docker run kho226/reading-list-backend go test -v -cover ./...
