version : '3'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev 
    ports:
      - "8080:8080"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev